name: gprs_to_address_web
description: A new Flutter project for web.
version: 1.0.0+1
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.3.1
  location: ^4.4.0
  share: ^2.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/white.jpg
